export default (function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 1040,
	height: 624,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"/src/movies/mansion/images/bmpbg.png", id:"bmpbg"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.bmpbg = function() {
	this.initialize(img.bmpbg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1040,624);


(lib.imgtext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#0943BA").p("AilCXQD3hOBWjBQAFAEAIAEQgsBghTBEQhTBHh2AmQgBAHgEADgAitirQBbAdAwAjIgJANQgxgkhXgdg");
	this.shape.setTransform(379.4,38.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1A1311").s().p("AilCYQD3hPBWjAQAEAEAJAEQgsBfhTBEQhUBIh1AlQgBAIgEACgAizieIAGgMQBbAdAwAjIgJAMQgxgkhXgcg");
	this.shape_1.setTransform(379.5,38.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#0943BA").ss(3).p("AFtFtIrZAAIAArZILZAAg");
	this.shape_2.setTransform(377.8,36.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AlsFtIAArZILZAAIAALZg");
	this.shape_3.setTransform(377.8,36.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#0943BA").p("ABxiJIAAETIgOAAIAAgVIjUAAIAAgOIDUAAIAAhtIjDAAIAAgOIDDAAIAAhnIjIAAIAAgOg");
	this.shape_4.setTransform(292.4,43.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1A1311").s().p("ABjCKIAAgWIjUAAIAAgNIDUAAIAAhtIjDAAIAAgNIDDAAIAAhoIjIAAIAAgOIDXAAIAAETg");
	this.shape_5.setTransform(292.4,43.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#0943BA").ss(3).p("AFtFtIrZAAIAArZILZAAg");
	this.shape_6.setTransform(292.5,36.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AlsFtIAArZILZAAIAALZg");
	this.shape_7.setTransform(292.5,36.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#0943BA").p("AiEi2QBJASA1AaIgGAOQg0gahJgSgAiNCjQB3grBJhAQBOhCAshmQAEAEAJAEQgsBmhPBDQhJBChxApQABADgCADQgBADgCABgAizhEQAeAHAmALQAkAMAXALIgGAOQgWgKglgMQglgMgfgHg");
	this.shape_8.setTransform(207.7,37.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1A1311").s().p("AiNCjQB2gqBJhBQBPhBAshmQAEADAJAFQgtBmhPBDQhIBBhxApQABADgCADIgEAFgAh2gjQglgLgegHIAFgOQAfAGAmAMQAkAMAXAKIgGAOQgWgKgmgMgAiJioIAFgOQBJATA1AaIgGAOQg0gahJgTg");
	this.shape_9.setTransform(207.7,37.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#0943BA").ss(3).p("AFtFtIrZAAIAArZILZAAg");
	this.shape_10.setTransform(207.2,36.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AlsFtIAArZILZAAIAALZg");
	this.shape_11.setTransform(207.2,36.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#0943BA").p("AilCXQD3hOBWjBQAFAFAIADQgrBghUBEQhTBHh1AmQgBAGgFAEgAitirQBbAdAwAjIgJANQgxgkhXgdg");
	this.shape_12.setTransform(123.5,38.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1A1311").s().p("AilCYQD3hPBWjAQAFAEAIAEQgsBfhTBEQhTBIh2AlQgBAHgEADgAi0ieIAHgMQBaAcAwAkIgIAMQgxgkhYgcg");
	this.shape_13.setTransform(123.5,38.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#0943BA").ss(3).p("AFtFtIrZAAIAArZILZAAg");
	this.shape_14.setTransform(121.9,36.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AlsFtIAArZILZAAIAALZg");
	this.shape_15.setTransform(121.9,36.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#0943BA").p("ADCiSQgBADgEAAQhCBliABaQAsAmA5A+IgMAKQglgqg9g1QhCg3g9giIAKgLQA8AjA2ApQA2gnAwgtQA1gyAeguIlrAAIAAgPIF1AAIADgCg");
	this.shape_16.setTransform(36.1,38.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#1A1311").s().p("AgNA/QhDg2g8gjIAJgKQA8AiA3ApQA2gnAwgsQA1gyAegvIlrAAIAAgPIF1AAIADgCIANANQgBACgEABQhCBliBBZQAsAnA5A9IgMALQgkgrg9g1g");
	this.shape_17.setTransform(36,38.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#0943BA").ss(3).p("AFtFtIrZAAIAArZILZAAg");
	this.shape_18.setTransform(36.6,36.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AlsFtIAArZILZAAIAALZg");
	this.shape_19.setTransform(36.6,36.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0943BA").s().p("AgJALQgGgFAAgGQAAgFAGgFQAEgEAFAAQAGAAAFAEQAEAFABAFQgBAGgEAFQgFAEgGAAQgFAAgEgEgAgGgGQgCADAAADQAAAEACADQADADADAAQAEAAADgDQADgDAAgEQAAgDgDgDQgDgDgEAAQgDAAgDADg");
	this.shape_20.setTransform(241.1,222.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0943BA").s().p("AgOAuIgFgDQAVgKACgTQgEAHgHAAQgGAAgEgEQgFgEAAgIQAAgFAFgFQAFgEAGAAQAGAAADAEIgBgQIgoADIgFABQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIgCgHIAOgBIAigCIAAgLIgBgHIAJABIACACIgBACIgBADIAAAJIAkAAIABABIAAAFQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgkAAIAAAWQABAEAAAHQAAAXgUAMIgDABgAgPAEQAAAKAJAAQAFAAABgDQADgDAAgEQAAgEgDgBQgBgCgEAAQgKAAAAAHg");
	this.shape_21.setTransform(233.2,218.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0943BA").s().p("AgiAhQAAgGAGgEQAFgEAKAAIAMABIgBgSQgOABgMgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgEQAKACARgBIAAgRQgSABgNgBIgBgBIAAgGQARABAPAAIAAgMIgBgIQADAAAEACQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgCAFIAAAKQAMAAAQgDIABAAIAAAFIAAACQgOACgPABIAAARQANgBAMgDIACABIAAAFIgCABQgNABgMABIABATQARAFANAKIABACIgDAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQgNgKgMgEQAAASgTAAQgUAAAAgOgAgbAhQAAAHAMAAQAIAAAEgEQACgDAAgGQgGgCgGAAQgOAAAAAIg");
	this.shape_22.setTransform(221.9,218.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0943BA").s().p("AgeAWIABgxIgBgRIAJACQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIgBADIgBALIgCAvQAAAJADAEQADADAHAAQATAAAVgVIACAGIAAACIgBACQgVATgVAAQgTAAAAgXg");
	this.shape_23.setTransform(211.1,218.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0943BA").s().p("AgjAzIgBgBIAAg9QgFAIgFAEIgBABIgEgDQAQgUAHgVIACgIIAHADIABABIgBACIgKAVIAABJIgBABgAAtAwQgNgJgLgPIABgBIADgCIACAAQAJAOAQAIIgFAGgAgUAvIgEgDQAMgIAIgKIAEgHIAEAEIABACIgFAFQgFAKgMAIIgCABgAgWAPIgBgBIAAgFIABgBIASAAIAAgYIgOAAIgBgBIAAgFIABgBIAOABIAAgJIgBgQIAGABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAACIgBAVIAWAAIgBgZIAIABIABABIgBACIAAAVIAQgBIABABIAAAFIgBABIgQAAIAAAYIAVAAIABABIAAAFIgBABgAABAIIAWAAIAAgYIgWAAg");
	this.shape_24.setTransform(199,218.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0943BA").s().p("AgVAxIgEgDQAOgKAFgUIABgGIAFABIAAACIAAABIAAADIgCAHQAEAKAKAEIAAghIgaAAIgBgBIAAgEIABAAIA+AAIABAAIAAAEIgBABIgeAAIAAAOIAXAAIABABIAAAEIgBABIgXAAIAAAPIAVACIANAAIgCAEQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgJAAQgSgBgKgEQgLgEgEgKQgGAMgIAHIgCABgAguAvIgCgEIAIAAQAFAAAAgFIAAgcIgHADIgEACIgCABIgBgBIgCgHIAKgCIAGgCIAAgYIgEAAIgLABIAAgBIAAgFIAAgBIALAAIAEAAIAAgJIgBgOIAHABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAABIgBACIgBATIABAAIAKAAIABABIAAAFIgBABIgKgBIgBAAIAAAVIAMgEIAAADQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAAAIgKAFIABAfQAAAHgEACQgCACgJAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBgAgHgIIAAgBIAAgjIAAgBIAuAAIABABIAAAjIgBABgAgBgOIAiAAIAAgKIgiAAgAgBgdIAiAAIAAgKIgiAAg");
	this.shape_25.setTransform(187.8,218.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#0943BA").s().p("AgrAbQAAgHAEgHIAFADQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQgDAFAAAEQAAAOAdAAQAPAAAPgEIACABIABAHIgBABQgSADgPAAQgjAAAAgVgAgOgFQgBgBgEgBQAIgGALgFIgLAAQgOAAgKgCQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIABgFQALACARAAQALABAMgCQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAGQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAQgOACgOALIgCABIgBgBgAAdgWQgEgIgJgGIAEgEIACAAQAHAGAFAIQABABAAAAQAAAAAAAAQAAAAAAAAQAAAAgBAAIgDADIgBABIgBgBgAAngdQgFgJgIgGIAEgDIABAAQAIAGAFAHIAAACIgDADIgBAAIgBAAg");
	this.shape_26.setTransform(177.2,218.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#0943BA").s().p("AglArQgEgMAAgVQAAgMAFgdIAAgLIAIADQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgCAFQgFAaAAAOIABAUIAIgTIACAFIAAADQgGAOAAAEIgBAFIAAABIgFACIgCgBgAgNAdQAAgGAFgEQAFgDAGAAIAMABIgBgeIgXAAIgCgBIAAgGQAMABANgBIAAgNIgBgKQAFAAAEACIABABIgBACIgBAFIAAANIASgDQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIABAEQAAABAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAIgTADIABAgQALAEAJAIIAAABIgDAFQAAAAAAABQAAAAAAAAQgBAAAAAAQAAgBAAAAQgGgFgKgFQgBAPgSAAQgQAAAAgNgAgGAdQAAAHAJAAQAMAAAAgKIAAgCIgNgCQgIAAAAAHg");
	this.shape_27.setTransform(165.2,218.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#0943BA").s().p("AgUAuQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIABhIIgBgSIAJABQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAABIgBAdQAUAGAPAIIABABIgDAGQAAAAAAAAQgBABAAAAQAAAAgBAAQAAgBAAAAQgRgKgOgDIAAAwQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_28.setTransform(154.5,218.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0943BA").s().p("AgkAkIgGgEQAXgLATgUQAKgJAJgTIggAAIgQABIgCgCIAAgHIAwABIAHgBQAAgBAAAAQAAAAABAAQAAAAAAABQABAAAAAAIAFAFQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDAEQgIAOgJAKQAPAKASARQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgEAEQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgMgOgUgPQgRATgVANIgCAAIgBgBg");
	this.shape_29.setTransform(142,218.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#0943BA").s().p("AgbAoIgGgHIAMgFQASgJALgKQAUgNANgRIACAIQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAgBABQgNANgRANQgNALgSAKIgFAEIgBAAIgCgBgAgVACQgHgEgOgGIADgFIACgBQALAEAJAGQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABIgDADIgBAAIgBAAgAgIgVQgIgIgNgFIAEgFIACgBQALAFAJAHQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAIgDAFIgBABIgBgBg");
	this.shape_30.setTransform(130.9,218.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#0943BA").s().p("AgcAoIgGgEQASgJAGgNQAFgMAAgOIgBgJQAGAAABABQABABAAAAQABAAAAABQAAAAAAAAQAAABgBAAIAAAGQAAAPgFANQgGAOgPAJIgCAAIgCAAgAAPgGIgGgDQAPgJAIgNIgyAAIgVABQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgBgIIAXABIAuAAQAGAAACgBIACAAIABAAIAFAFQAAAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAIgCADQgJANgNAJIgCABIgBgBg");
	this.shape_31.setTransform(119.6,218.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#0943BA").s().p("AgMAwIgDgDQAVgMAHgYIABgGIgSABIgBgBIAAgDIABgBIATAAIACgTIgPAAQgCAHgBAFIgCACIgCgBIgDgCQAHgLABgSIABgFIAHACQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIgBABIgBAEIgDAIIANAAIgBgWIAIAAIABACIgBACIgBASIAWAAIABABIAAAFIgBABIgWAAQAAAKgCAJIAbAAIABABIAAADIgBABIgZgBQAJAbAUANIgEAFIgBABIgCgBQgRgPgJgYQgHAbgUANIgCABQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAgBgBgAgwAvIgCgHIALgCIAJgCIAAghIgQAAIAAgBIAAgCIAAgBIAQAAIAAgMIgKAAIgBgBIAAgEIABgBIAcAAIACABIAAAEIgCABIgLAAIAAAMIACAAIAMAAIABABIAAACIgBABIgOAAIAAAfIAQgGIAAAFQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgfAKIgDACIgCABgAgpAeQgBgIgDgJQAAgBAAAAQAAAAAAAAQAAAAAAAAQABgBAAAAIACgBQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAQAEAIABAJIgBACIgEABIAAAAIgBgBgAgQAbIgDgBIAEgNIABgEIAGACIABABIgBABIgBACIgEALQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAIgBAAgAgxgRIgCgEQAPgKAFgMIADgGIAGACIACABIgBABIgBABQAHAJAKAIIgDADIgBACIgCgBQgKgKgEgGQgHALgNAMIgCABg");
	this.shape_32.setTransform(108.2,218.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#0943BA").s().p("AgUAuQgHgDgEgIQgFAGgGAFIgDACIgBABIgCgBIgCgGIAHgEIAKgJIAAgcIgRAAIAAgBIAAgDIAAgBIAXAAIABABIgBAgQADAIAHADQAHADAOAAQAbAAAVgCIgDAFQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgoACQgTAAgIgEgAAHAnIgCgBIABgaQgHALgQAJIgBAAIgFgFQASgHAIgMIgRAAIAAgBIAAgRIAAgBIAxAAIABABIgBAKIABAHIgBABIgVAAQAFAHAHAEIAJgIIADgEIAGAEIAAABIgBABIgEACIgJAHQAKAFAJADIgDAEQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgXgKgIgNIAAAaIgBABgAgIADIAlAAIAAgIIglAAgAgXgRIgBgBIAAgEIABgBIAeAAIAAgJIgWAAIgBgBIAAgEIABgBIAWAAIgCgLIAHABIACABIgBABIAAAIIAZAAIABABIAAAEIgBABIgZAAIAAAJIAhAAIABABIAAAEIgBABgAghgXQgHgLgFgFIAAgCIADgCIABAAQAIAGAGAKQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgDACIgBAAIgBAAg");
	this.shape_33.setTransform(96.9,218.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#0943BA").s().p("AgVAfQAAgPAXgMQAAgJgHABQgIgBgLAIIgLAKQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgEgEIAAgCQARgMAJgSIgVABIgBgBIgBgHQANABANgBIAFgLIAAgGIAHACQAAABABAAQAAAAAAABQAAAAAAAAQAAABgBAAIgBADIgDAJIAWgEIACABIAAAEIgBACIgaAEQgGALgGAGIABAAQAGgFAIAAQALAAABALIASgGQAFgCAEgEIAFAHQAAAAAAABQAAAAAAABQAAAAAAAAQgBAAAAAAIgGACIgYAIIAAATQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABgBAAIgFAAQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIABgRQgRAKAAAJQAAAKARAAQAOgBANgCIACABIAAAFQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAQgQACgMAAQgYAAAAgQg");
	this.shape_34.setTransform(85.3,218.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#0943BA").s().p("AgKAtIgHgDQAVgNAJgQQAKgNAEgTIg2AAIAAAXQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAQgDABgDgBQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgdQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIAdAAIAAgGIgBgNIAHABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQgCACAAAHIAAAGIASAAQAJAAABgBIADAAQACABACAEQAAAAABABQAAAAAAAAQAAABAAAAQgBABAAAAIgCAEQgFASgIANQgLASgRALIgCABIgBgBg");
	this.shape_35.setTransform(74.1,218.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#0943BA").s().p("AgnAZIgHgDQAUgQAHgSIAEgMIAJADQAAABAAAAQABAAAAABQAAAAgBABQAAAAAAABQgCABgCAFQgKAVgQAOIgCABIgBAAgAAnAVQgLgYgRgRIAFgDIACAAQASARALAWQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgFAEIgBAAIgBgBg");
	this.shape_36.setTransform(62.3,218.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#0943BA").s().p("AgKAtIgHgDQAVgNAJgQQAKgNAEgTIg2AAIAAAXQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAQgDABgDgBQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgdQAAgBAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIAdAAIAAgGIgBgNIAHABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQgCACAAAHIAAAGIASAAQAJAAABgBIADAAQACABACAEQAAAAABABQAAAAAAAAQAAABAAAAQgBABAAAAIgCAEQgFASgIANQgLASgRALIgBABIgCgBg");
	this.shape_37.setTransform(51.4,218.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#0943BA").s().p("AgbAoQgDgDgDAAQAVgOANgUQALgMAIgRQADgGAAgIQAEABAGAEQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABIgFAIQgIASgLAOQgPAUgSAMIgBABIgCgBg");
	this.shape_38.setTransform(39.3,218.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#0943BA").s().p("AgMAsQgFgEAAgHQAAgGAFgEQAFgEAHAAIALABIgCgbQAFAAADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIgBACIABAZQAMAEAKAHQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAAAABIgCAFQgBAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAgBQgHgGgKgFQAAASgTAAQgHAAgFgDgAgLAhQAAAHALAAQALAAAAgKIAAgDIgLgCQgLAAAAAIgAgmAdIgEgEIAAgBQANgUAIgVIgOABIgGAAIgCgCIAAgFIAJAAIAPgBIADgNIABgJIAJACIABACIgBABIgBAEIgEAMIAOgDQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAAAIABAFQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgRAEQgLAbgMATIgBAAIgBAAgAAogHQgKgHgNgFIADgFIABgBQAOAFAJAGQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgDAFIgBAAIAAAAg");
	this.shape_39.setTransform(28.5,218.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#0943BA").s().p("AAFAmQgEgEgBgLQAAgQgIAAQgHAAgIAKQgFAGgJATQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgFgDQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAWgnANgcQAEgJAAgFIAHAFQAAAAABABQAAAAAAABQAAAAAAAAQgBABAAAAIgCAFIgWAnIABAAQAIgIAIAAQALAAADATQABAQAIAAQAHAAAHgIQAGgHAEgMQACAEACACQAAAAAAABQABAAAAAAQAAABAAAAQAAABgBAAQgDAIgGAIQgHAKgMAAQgIAAgEgGg");
	this.shape_40.setTransform(17.2,218.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#0943BA").s().p("AAUAuQgcgDAAgUQAAgQASgHIAAgBQgZAEgTAHIgEABIgBgBIgCgGIAEgCQAHgCAFgDQASgOASgUIgaAEIgHADIgCgDQgBgBgCgFIAKAAIAcgFQABAAAAAAQABAAABAAQAAAAABAAQAAgBAAAAIACAAIACABIAEADIABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAABIgFACQgUAUgTAOIABAAQAegJAegDQAAAAAAAAQABAAAAAAQAAAAAAAAQABAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgKABgLAEQgVAGAAAQQAAAQAcAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIgBAFQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_41.setTransform(5.6,218.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#0943BA").s().p("AgKALQgEgFgBgGQABgFAEgFQAFgEAFAAQAGAAAEAEQAFAFABAFQgBAGgFAFQgEAEgGAAQgFAAgFgEgAgGgGQgCADAAADQAAAEACADQAEADACAAQADAAAEgDQACgDAAgEQAAgDgCgDQgEgDgDAAQgCAAgEADg");
	this.shape_42.setTransform(229.7,202.8);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#0943BA").s().p("AgDAyIAAgBIAAgoQgOAUgbANIgCABIgFgGQAdgLAQgVIgoAAIgBgBIAAgEIABAAIArAAIgBgRIAGABQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAAAIgBACIAAANIAsAAIABAAIAAAEIgBABIgpAAQAOAUAhAMIgDAEIgCACIgBgBQgfgMgNgVIAAAoIgBABgAAngFIgBgBIAAgOIhLAAIAAAOIgBABIgFAAIgBgBIAAgUIABgBIA8AAQAFgIAEgJIABgFIAHADIABABIgBABIgCADIgIAOIAVAAIABABIgBAFIABAPIgBABgAgZgeIgIgOQAAAAgBgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAEgBQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAFAFAEAJQAAABAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAIgDABIgBABIgBgBgAAAgfQgCgJgFgGQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIADgBQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAEAIACAHQABABAAAAQAAAAAAAAQgBAAAAABQAAAAgBAAIgDABIgBAAIAAAAg");
	this.shape_43.setTransform(221.8,199.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#0943BA").s().p("AApAwQgTgKgMgPQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIAEgCIABAAQAPARASAHIgEAEIgCACgAgsAvIgEgDQARgIAJgKIAFgIIAGADIABACIgBABIgDADQgLANgQAIIgCABgAgvANIgBgBIAAgFIABgBIAbABIAAgYIgWAAIAAgBIAAgFIAAgBIAWAAIAAgJQAAgLgBgEIAHABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAABIgBACIAAAUIAaAAIgBgYIAIABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIgBACIAAAUIAXAAIABABIAAAFIgBABIgXAAIAAAYIAcgBIABABIAAAFIgBABgAgNAHIAaAAIAAgYIgaAAg");
	this.shape_44.setTransform(210.5,199.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#0943BA").s().p("AgGAGQgCgDAAgDQAAgIAIAAQADAAADACQADAEAAACQAAADgDADQgDADgDAAQgCAAgEgDg");
	this.shape_45.setTransform(199.1,199.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#0943BA").s().p("AgeAzIgBgBIABgvIgNAMIgBABIgCgBQgBgDgCgBQALgJAIgHIgBgHIAFABQAFgHAFgKIgeAAIgBgBIAAgFIABgBIAhABIADgIIACgIIAHABIABACIgBACIgCAEIgDAHIA3gBIABABIAAAFIgBABIg5AAQgHANgIAMIAAA1IgBABgAAAAvIgCgFIAKABQAFAAAAgEIAAgWIgbAAIgBgBIAAgFIABgBIAbABIAAgDIgBgIIAEAAQAJgEAGgFIgnAAIgBAAIAAgFIABgBIApAAIACAAIACAAIADACIACADQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgWANIAAAGIAdgBIABABIAAAFIgBABIgdAAIABAYQAAAFgDACQgDACgNAAQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBg");
	this.shape_46.setTransform(187.6,199);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#0943BA").s().p("AApAwQgTgKgMgPQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBABAAIADgCIACAAQANAQATAIIgEAEIgCACgAgsAvIgEgDQASgJAJgJIAEgIIAHADIABACIgFAEQgLANgQAIIgBABgAgvANIgBgBIAAgFIABgBIAbABIAAgYIgVAAIgBgBIAAgFIABgBIAVAAIgBgYIAIABIABABIgBACIAAAUIAaAAIAAgYIAHABIACABIgBACIgBAUIAXAAIABABIAAAFIgBABIgXAAIAAAYIAcgBIABABIAAAFIgBABgAgNAHIAaAAIAAgYIgaAAg");
	this.shape_47.setTransform(176.3,199.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#0943BA").s().p("AAEAkIgEgEQAkgHgBgbQABgMgJgIQgJgIgMAAIgCAAQgDAegKARQgHAMgKAAQgHAAgFgHQgEgHAAgMQAAgPANgMQAMgNAUAAQATAAALAKQAKAKAAARQAAAcgkAJIgBABQAAAAgBAAQAAgBAAAAQAAAAAAAAQAAAAgBgBgAgYgTQgLAKAAAMQAAAJADAFQACAEAEAAQAGAAAFgIQALgSACgZQgOACgIAJg");
	this.shape_48.setTransform(165,199.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#0943BA").s().p("AgfAYQAAgPAWgLQgFgPgBgPQgBgHgCgEIAKABIABACIgBAEIABAHIAEAXIATgKQAFgDABgCIAGAGQABAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgKAEIgYALQgRAJAAALQAAAHAHADQAGADAMAAQAPAAAOgDIACABIAAAGQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgTACgMAAQgfAAAAgUg");
	this.shape_49.setTransform(153.6,198.9);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#0943BA").s().p("AgEAuIgGgEQALgGAHgJQAJgNAAgUIgBgbIgCgMIAIABQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIgBAFIACAeQAAAXgKAMQgHAKgJAHIgCAAIgBAAgAgVANQgDgGAAgNIADgbQABgHAAgFIAIADIABABIAAACIgCAEQgDANgBANIABALIAIgOIADAEQAAABAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIgHANIAAAEIgBACIgGABQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBg");
	this.shape_50.setTransform(142.1,199.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#0943BA").s().p("AguArQAHgKACgLQADgMAAgVIAAgiIABgBIBPAAIABABIAABSQAAAFgDADQgDACgLAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIgCgGIAKABQAEAAAAgFIAAhKIhCAAIAAAcQAAAWgCANQgDALgGALIgBABgAgNAkIAAAAIAAgfIAAgBIAlAAIAAABIAAAdIAAABIgFAAIgBgBIAAgEIgZAAIAAAGIgBAAgAgHAYIAZAAIAAgOIgZAAgAgTgDIgBgBIAAgEIABgBIAUAAIAAgLIgQAAIgBgBIAAgEIABgBIAQAAIAAgBIgBgJIAIAAIABABIgBACIAAAGIAAABIATAAIABABIAAAEIgBABIgTAAIAAALIAYAAIABABIAAAEIgBABg");
	this.shape_51.setTransform(130.4,199.4);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#0943BA").s().p("AgKALQgEgFgBgGQABgFAEgFQAFgEAFAAQAGAAAEAEQAGAFAAAFQAAAGgGAFQgEAEgGAAQgFAAgFgEgAgGgGQgCADAAADQAAAEACADQADADADAAQAEAAADgDQACgDAAgEQAAgDgCgDQgDgDgEAAQgDAAgDADg");
	this.shape_52.setTransform(116,202.8);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#0943BA").s().p("AgrAwIgBgBIAAhdIABgBIAmAAIAAABIAAAhIAAABIggAAIAAA7IgBABgAglgSIAZAAIAAgJIgZAAgAglghIAZAAIAAgIIgZAAgAAZAtIgCgFIAJAAIAFgBQAAAAAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIAAgvIghAAIgBgBIAAghIABgBIAnAAIABABIAABSQAAAGgDACQgCADgMAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAgAAKgSIAcAAIAAgJIgcAAgAAKghIAcAAIAAgIIgcAAgAgRAoIgBgBIAAgpIABgBIALAAIALAAIAMAAIABABIAAAnIgBABIgFAAIgBgBIAAgEIgXAAIAAAGIgBABgAgMAbIAXAAIAAgLIgXAAgAgMALIAXAAIAAgKIgXAAg");
	this.shape_53.setTransform(108.1,199.3);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#0943BA").s().p("AguAwIgBgBIAAgFIABgBIAsAAIAAgWIgfAAIgBgBIAAgEIABgBIBEAAIABABIAAAEIgBABIghAAIAAAWIAtAAIABABIAAAFIgBABgAgoAHIgEgDQAYgEAFgQIABgHIAHACQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIgBABIgCAFQgFAPgWAHIgBAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBgAAHABQgCgBAAgFIgBgSIAHABQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIgCACIAAAMQAAAFACAAQACACAHAAQAHAAADgCQACgCAAgIIAEACQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQgBAHgEABQgDADgKAAQgLAAgEgDgAgrgMIgBAAIAAgVIABgBIAoAAIAAgNIAFABQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIgCACIAAAJIAqAAIABABIAAATIgBABIgFAAIgBgBIAAgOIhLAAIAAAQIgBAAg");
	this.shape_54.setTransform(96.7,198.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#0943BA").s().p("AgSAfQAAgEAEgEQADgDAGAAQAOAAADAQQARgGAAgPQAAgIgGgFQgFgDgJAAQgOAAgPALQgFADgFAGQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgEgEQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAMgKAOgOIAUgYIgbAFIgGABIgBgBIgDgIIAKAAIAagEIAEgBIABgBIACABIAFAFIABACQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgFAEIgbAeIAAAAQAMgHALAAQAMAAAHAHQAHAEAAAMQAAANgJAHQgLAJgRAAQgSAAAAgOgAgMAfQAAAHAMAAIAFAAQgCgMgIAAQgHAAAAAFg");
	this.shape_55.setTransform(85.2,199.2);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#0943BA").s().p("AgPAoQgFgEgBgKIgBgcIgQACIgGABIgBgBIgCgFIAZgEIAAgNIgBgLQAFAAAEACIACABIgBADIgCARIAfgEIAAgUIgBgJIAJACIACABIgBACIgBAEIAAAUIAXgCQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAAFQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgXABIgCAQQgBAMgLAAIgJgBQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgGIAJABQAGAAAAgGIABgOQgVACgKACIABAbQAAAIAEACQAEACAKAAQAMAAAQgCQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAABAAIAAAGQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAQgJACgSAAQgOAAgHgEg");
	this.shape_56.setTransform(73.9,198.9);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#0943BA").s().p("AgrAaQAAgGAEgHIAFADQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQgDAFAAAEQAAAOAdAAQAPAAAPgEIACACIABAFIgBACQgSADgPAAQgjAAAAgWgAgOgEQgBgCgEgBQAIgGALgGIgLABQgOAAgKgCQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIABgHQALADARAAQALAAAMgBQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAGQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAQgOACgOALIgCABIgBAAgAAdgWQgEgHgJgIIAEgCIACAAQAHAGAFAHQAAABABAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgDAEIgBAAIgBgBgAAngdQgFgKgIgFIAEgDIABAAQAIAGAFAHIAAACIgDADIgBAAIgBAAg");
	this.shape_57.setTransform(63.4,198.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#0943BA").s().p("AgTAsQgIgEgDgIIgNALIgDAEIgBgBIgEgGIAHgEIAKgJIAAgbIgIAAIgHAAIgCAAIAAgFIACgBIAVAAIABABIAAAgQACAHAIAEQAGADAPAAQAaAAAVgDIgBAFQgBABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgpABQgSAAgHgDgAAbAfIgCgFIAIABQAEAAAAgEIAAgdIgvAAIAAAmIgBABIgGAAIAAgBIAAgrIAAgBIAIAAIAAggIABgBIAqAAIABABIAAAgIAHAAIABABIAAAjQABAFgDACQgDACgIAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBgAAPgMIAOAAIAAgMIgOAAgAAIgMIAAgRIABgBIAUAAIAAgJIgfAAIAAAbIAKAAgAAQAWIgIAAIgIABIAAgBIAAgWIAAAAIAZAAIABAAIgBAIIABAOIgBABIgJgBgAAEARIAQAAIAAgNIgQAAgAghgaQgHgKgGgGIAAgBIABgBIACgBIADgBQAHAHAGAJIgBACIgDACIgBABIgBgBg");
	this.shape_58.setTransform(51.4,199.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#0943BA").s().p("AAUAtQgTgUgWgSQgFgEAAgDQAAgCAEgEIAeggQADgDACgEIAHAFIABACQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEADIggAgIgBACQAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAQAZAUARASQAAAAAAAAQAAABABAAQAAAAAAABQAAAAgBAAIgEAEIgBABIgBgBg");
	this.shape_59.setTransform(39.6,199.1);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#0943BA").s().p("AgkAfQAAgGAHgFQAGgDAJAAIAMAAIgCg0IgBgJIAHABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAIgBAHIgBARQAPgCAOgFIABABIACAGIgBABQgOAEgRACIADAdQASAEAOAKIABACIgEAFIgBAAQgPgKgNgEIAAADQAAAIgEAEQgFAEgKAAQgVAAAAgOgAgdAfQgBAHAOAAQAOAAABgLIAAgDIgOgBQgPAAABAIg");
	this.shape_60.setTransform(28.4,199.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#0943BA").s().p("AAQAwIgDgFIALABQAEgBAAgEIAAgdIgoAAIgBgBIAAgEIABgBIAoAAIgBgKIAIABIABABIgBACIAAAGIAPAAIAAABIAAAEIAAABIgPAAIAAAeQAAAGgDACQgDACgLABQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBgAgsAvIgCgEIAIAAQAEAAAAgGIAAgaIgGACIgFADIgBAAIgBgBIgCgGIAKgDIAFgCIAAgYIgDAAIgLABIgBgCIAAgEIABgBIAOAAIAAgJIgBgOIAIAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAAAAAAAIAAADIgBAKIAAAJIALAAIABABIAAAEIgBACIgLgBIAAAAIAAAVIAMgEIAAADQAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBAAIgKAFIAAAeQAAAIgDABQgDACgIAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBgAAGAkQgGgMgDgDQAAAAgBAAQAAgBAAAAQAAAAABAAQAAgBAAAAIADgCIAAAAQAGAFAGAJQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBABIgDADIgBAAIgBAAgAgNgHIgBgBIAAgFIABgBIAZAAIAAgOIgUAAIgBgCIAAgEIABgBIAUABIgBgQIAIABIABABIgBADIAAALIAYgBIABABIAAAEIgBACIgYAAIAAAOIAfAAIAAABIAAAFIAAABg");
	this.shape_61.setTransform(17,199.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#0943BA").s().p("AAaAiQgDgOAAgUIhCAAIgBAAIAAgEIABgBIBIAAIABABIAAAPQAAALACAKQADALAEAAQADAAACgPIAEADQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABQgDARgIAAQgJAAgEgRgAgtAwIgDgEQAUgHANgMIgRgNIABgCIACgCIACAAIARAMIAJgLIABgFIAFADIABABIgBACIgKAOIAPAQIAAACIgDADQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgPgRQgLAKgUAKIgCABQgBAAAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAgAgxgRQAOgMAHgQIABgFIAHACIABACIgBABIgCACIgDAHIBCgBIABABIAAAFIgBABIhGAAQgFAIgIAIIgCABgAgbgPIgBgBIAAgEIABgBIA5AAIABABIAAAEIgBABg");
	this.shape_62.setTransform(5.9,199);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#0943BA").s().p("AgKALQgFgFABgGQgBgFAFgFQAFgEAFAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgFgGQgDADgBADQABAEADADQACADADAAQADAAADgDQAEgDAAgEQAAgDgEgDQgDgDgDAAQgDAAgCADg");
	this.shape_63.setTransform(161.5,183.3);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#0943BA").s().p("AAFAmQgEgEgBgLQAAgQgIAAQgHAAgIAKQgFAGgJATQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgFgDQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAWgnANgdQAEgHAAgFIAHAEQAAABABAAQAAAAAAABQAAAAAAAAQgBABAAAAIgCAFIgWAnIABAAQAIgIAIAAQALAAADATQABAQAIAAQAHAAAHgIQAGgHAEgMQACAFACABQAAAAAAABQABAAAAAAQAAABAAAAQAAABgBAAQgDAJgGAGQgHALgMAAQgIgBgEgFg");
	this.shape_64.setTransform(153.7,179.6);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#0943BA").s().p("AgOAoQgHgEAAgKIgBgcIgQACIgFABIgDgBIgCgFIAagEIAAgNIgBgLQAGAAADACIABABIAAADIgBARIAegEIAAgUIgBgJIAJACIACABIgBACIgBAEIAAAUIAXgCQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAABAAIAAAFQgBABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgYABIgBAQQgCAMgKAAIgIgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgGIAKABQAFAAAAgGIABgOQgVACgJACIAAAbQABAIADACQAEACAKAAQALAAAQgCQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIABAGQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAQgJACgTAAQgOAAgFgEg");
	this.shape_65.setTransform(142.1,179.4);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#0943BA").s().p("AgiAhQAAgGAGgEQAFgEAJAAQAKAAADABIgBgSQgOABgMgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgEQAKACARgBIAAgRQgSABgNgBIgBgBIAAgGQARABAPAAIAAgMIgBgIQADAAAEACQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgCAFIAAAKQAMAAAQgDIABAAIAAAFIAAACQgOACgPABIAAARQANgBAMgDIABABIAAAFIgBABQgNABgMABIABATQARAFANAKIABACIgDAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQgNgKgMgEQgBASgSAAQgUAAAAgOgAgbAhQAAAHAMAAQAIAAAEgEQACgDAAgGQgGgCgHAAQgOAAABAIg");
	this.shape_66.setTransform(130.9,179.6);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#0943BA").s().p("AgEAuIgGgEQALgGAHgJQAJgNAAgUIgBgbIgCgMIAIABQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIgBAFIACAeQAAAXgKAMQgHAKgJAHIgCAAIgBAAgAgVANQgDgGAAgNIADgbQABgHAAgFIAIADIABABIAAACIgCAEQgDANgBANIABALIAIgOIADAEQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgHANIAAAEIgBACIgGABQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBg");
	this.shape_67.setTransform(119.4,179.7);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#0943BA").s().p("AAHAtIgEgEQAOgCAIgGQAKgHAAgLQAAgPgTgDQgLASgJALIACAGIgBACIgEACQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIgCgGQgMAKgKAAQgKAAAAgMQAAgJAHgJQAIgKAMgEIABgSIgOABIgFgBQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgFIAWAAIABgKIgBgIIAJACIABACIgCAGIgBAHQAOgBAQgEIABABIABAEQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQgOADgRACIgBAQQAJgDAKAAIACgKIAGADIACACIgCACIgBADQALACAHAHQAHAGAAAKQAAAXghAIQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBgAgjAbQAAAGAFAAQAHAAALgJQgDgMAAgLQgUALAAAPgAgIAAQAAAKACAJQAIgLAHgMQgJAAgIAEg");
	this.shape_68.setTransform(108.1,179.6);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#0943BA").s().p("AglArQgEgMAAgVQAAgMAFgdIAAgLIAIADQABAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABIgCAFQgFAaAAAOIABAUIAIgTIACAFIAAADQgGAOAAAEIgBAFIAAABIgFACIgCgBgAgNAdQAAgGAFgEQAFgDAGAAIAMABIgBgeIgXAAIgCgBIAAgGQAMABANgBIAAgNIgBgKQAFAAAEACIABABIgBACIgBAFIAAANIASgDQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIABAEQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAIgTADIABAgQALAEAJAIIAAABIgDAFQAAAAAAABQAAAAgBAAQAAAAAAAAQAAgBAAAAQgGgFgKgFQgBAPgSAAQgQAAAAgNgAgGAdQAAAHAJAAQAMAAAAgKIAAgCIgNgCQgIAAAAAHg");
	this.shape_69.setTransform(97,179.7);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#0943BA").s().p("AgCAgQgNgJAAgQQAAgWAagOIAAgBIgzAKIgCABIgCgBIgDgIIBSgLIACABIABAGQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAgBAAQgKABgGACQgNAFgHAKQgHAKAAAJQAAAYAfACIABABIAAAGQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAQgRgBgIgHgAAiACQgGgHgIgFIAFgDQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAABABAAQAGAEAHAJIgBAAIgDACIgBABIAAgBgAArgEQgEgIgJgGIAEgDIABAAQAIAGAFAHIAAACIgDACIgBABIgBgBg");
	this.shape_70.setTransform(85.6,180);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#0943BA").s().p("AgRAxIgCgFIAKAAIAGgBQAAAAAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIAAgHIgkAAIAAgBIAAgEIAAgBIAkABIAAgJIguAAIgBgBIAAgEIABgBIAuABIAAgIIgkAAIAAgBIAAgEIAAAAIAkAAIAAgGIgfAAIgBgBIAAgGIAAgLIABgBIAfAAIAAgHIgtAAIgBgBIAAgEIABgBIAtAAIAAgMIAFABIABABIAAACIgBAIIAtAAIABABIAAAEIgBABIgtAAIAAAHIAfAAIABABIAAALIAAAGIgBABIgfAAIAAAGIAjAAIAAAAIAAANIALgBIABABIAAAEIgBABIgLAAIAAASIAAAAIgGAAIAAAAIAAgEIgdAAIAAAIQAAAHgDACQgBACgMAAQgBAAgBAAQAAgBgBAAQAAAAAAAAQAAgBgBAAgAADAbIAdAAIAAgJIgdAAgAADANIAdAAIAAgIIgdAAgAADgLIAaAAIAAgJIgaAAgAgcgLIAaAAIAAgJIgaAAg");
	this.shape_71.setTransform(74,179.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#0943BA").s().p("AgtAwIgEgFQAagKAMgXQAEgKACgKIgpAAIgBgBIAAgGIABgBIAqABIAAgfIAGABQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIgBACQgBACAAAGIgBATIAugBIABABIAAAGIgBABIgsAAQANAnAiANIgEAFIgBACIgCgBQgggSgLgiQgBAIgEAJQgLAWgaAOIgBAAIgCgBg");
	this.shape_72.setTransform(62.6,179.6);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#0943BA").s().p("AgSAtQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIgBgHQAHADAGAAQAFAAACgGQADgLAAgVQAAgFgBgCQgCgDgCAAQgHAAgGACQgJAbgOAYQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgEgDIgBgCQAOgYAIgWIgPACQgDAAgCACQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAIgCgIIAcgCIAEgRIABgLIAJADQAAABABAAQAAABAAAAQAAAAAAABQAAAAgBAAIgCAEIgFARIALgBQANAAAAAQQAAAYgGANQgEAJgHAAQgIAAgEgCgAAkAKQgFgPgNgMIAFgDQAAAAAAAAQABAAAAAAQAAAAAAAAQABAAAAAAQAMAKAGAQQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgFAEIgBAAIgBgBgAAigUQgGgKgHgFIAEgDIABAAQAHAFAGAJIAAABIgDADIgBAAIgBAAgAAsgcQgFgIgIgGIAEgDQAAgBAAAAQAAAAABAAQAAAAAAAAQAAAAAAABQAIAFAFAIQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgDADIgBAAIgBAAg");
	this.shape_73.setTransform(51.6,179.3);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#0943BA").s().p("AAAAtIgEgDQAMgGAFgNQADgKAAgOIAAgMIgQABIgIAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIgBgGIAaAAIgBgRIgCgJIAKABIABACIgBACIAAAEIAAAQQAIgBAIgCQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAFIgBABIgRADIAAAOQABAQgFAMQgFALgLAGIgCACgAgiAoQgGgNAAgUQAAgPADgSIABgSQAGACACACIABABIgCAJQgEAaAAAJQAAAOACAIIAIgTIADAGIABABIgIATIAAACIAAADIgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAIgCgBg");
	this.shape_74.setTransform(40.2,179.7);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#0943BA").s().p("AAAAoQgEgFgBgLIAFAAIAAABQAAAOAVAAIARgCIABABIABAFQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgOABQgSAAgGgGgAgrArIAAgBQANgbAIgcQgLABgMAAIgCgBIgBgGIAIAAIAUgBIADgPIABgKIAJACIABACIgBABIgFASQAFAAALgEIABABIABAEQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgTAFQgKAggMAbIgBABgAABgDQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAQAIgCAMAAIAOABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAAAFQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgPAAQgJAAgLABgAAigUQgHgKgHgEIAFgDIABAAQAGAEAHAJIgBACIgDACIAAABIgBgBgAAsgcQgGgJgIgFIAEgDIABAAQAJAHAEAGQABABAAAAQAAAAAAAAQAAAAgBAAQAAABAAAAIgDACIgBAAIAAAAg");
	this.shape_75.setTransform(28.7,179.5);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#0943BA").s().p("AgbAzIAAgBIAAgmIgKAFIgGADIgBgBIgDgGIAUgHIAAgZIgKAAIgEAPIgBACIgCgBIgDgBQAEgMABgSIAAgGIAGABIABABIAAABIgBAMIAJAAIAAgJIgBgQIAHABIABABIAAACIgBAMIAAAJIABAAIALAAIABABIAAAEIgBABIgMAAIAAAVIAMgEIABACQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAABIgLAFIABApIgCABgAAUAxQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAgBgBIgBgFIANABQAHAAACgMQADgTABggIgGAAQgLAsgbAVIgDABIgBgBIgEgDQAegWAJgoIgLAAQgHAYgRAPIgCABIgBgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQASgPAHgVIgLAAIgHANIgCABIgBgBIgEgCQALgMAFgSIACgKIAGACQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIgBACIgDAFIgEANIAqAAIABABIAAAIQAAAfgEATQgCARgMAAIgKAAg");
	this.shape_76.setTransform(17,179.6);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#0943BA").s().p("AgzAtQAKgIAHgJQgGgJgCgKQgBgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIADgCQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAQADAKADAHQAHgNACgNIgNAAIgDADIgBAAIgDAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAABAAQAIgMALgVIgVAAIgBgBIAAgEIABgBIAYAAIABgBIADADQAAAAABAAQAAABAAAAQABABAAAAQAAAAAAABIgEAGIgMAVIAJAAIADgBIACAAIACACIACADIgBABIgBAEQgEARgGALIABACQAMALAUAAQAbAAASgCIgCAFQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQgRACgVAAQgYAAgMgMIgDgDQgHAJgHAHIgCABgAALAlIgBAAIAAgMIgYAAIgBgBIAAgEIABgBIAYAAIAAgKIgTABIAAgBIAAgEIAAgBIATAAIAAgHIgSAAIgBgBIAAgEIABgBIASAAIAAgJIgZAAIgBgBIAAgEIABgBIAZAAIAAgJIgRABIgBgBIAAgFIABAAIARAAIAAgLIAHABIABABIAAABIgBAIIAXAAIACAAIAAAOIAJAAIABABIAAAEIgBABIgJAAIAAAOIgCABIgXAAIAAAHIAZAAIABABIAAAEIgBABIgZgBIAAAKIAfAAIAAABIAAAEIAAABIgfAAIAAAMIAAAAgAARgJIATAAIAAgJIgTAAgAARgYIATAAIAAgJIgTAAg");
	this.shape_77.setTransform(5.6,179.5);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#0943BA").s().p("AgKALQgFgFABgGQgBgFAFgFQAFgEAFAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgFgGQgEADAAADQAAAEAEADQADADACAAQAEAAACgDQADgDABgEQgBgDgDgDQgCgDgEAAQgCAAgDADg");
	this.shape_78.setTransform(275.2,163.8);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#0943BA").s().p("AgSAfQAAgEAEgEQADgDAGAAQAOAAADAQQARgGAAgPQAAgIgGgFQgFgDgJAAQgOAAgPALQgFADgFAGQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgEgEQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAMgKAOgOIAUgYIgbAFIgGABIgBgBIgDgIIAKAAIAagEIAEgBIABgBIACABIAFAFIABACQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgFAEIgbAeIAAAAQAMgHALAAQAMAAAHAHQAHAEAAAMQAAANgJAHQgLAJgRAAQgSAAAAgOgAgMAfQAAAHAMAAIAFAAQgCgMgIAAQgHAAAAAFg");
	this.shape_79.setTransform(267.2,160.2);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#0943BA").s().p("AAAAtIgEgDQALgGAFgNQAEgIAAgQIAAgNIgYABIgBgBIgBgGIAaAAIgBgSIgBgIIAJACIABABIAAACIgBAEIAAAQQAIAAAIgDQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIABAFIgBACIgSACIABAPQgBARgFAKQgDAJgMAJIgCABgAgiAoQgHgNAAgUQAAgKAEgWQABgNAAgFQAFAAADADIACABIgBACIgCAGQgEAYgBAMQAAAMADALIAIgTIADAEIABACIgBADIgGAQIgBADIAAABIAAABIgFACIgCgBg");
	this.shape_80.setTransform(256.4,160.2);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#0943BA").s().p("AgfAzIgBgBIABguIgLAAIgFABIgBABQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgBgEIAIAAIAJgMIgRgRIABgCIABgCIACAAIAFADIAIgPQACgCAAgDIAGADIACABIgBABIgNAUIAHAIIAKgPIACgGIAGADIABABIgBACIgEAEIgTAcIARgBIgDgIQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAABAAIACgBIACAAQAFALACAGQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgDABQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAIgBgHIgJACIAAAuIgBABgAgMAxIgEgEQAWgHAAgXIAAgKIAGABIACABIgCAIQAAANgEAHQgFAJgMAFIgBABIgCgBgAAZAwQgDgCAAgGIgBgjIAHABIABABIAAADIgBAcQAAABAAABQAAAAABABQAAAAAAABQAAAAAAAAIAGABQAHAAABgDQACgDAAgIIAEACQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQAAAJgEAEQgCADgKAAQgHAAgDgBgAguAqIgEgCQAEgJACgMIAAgGIAGABIABABIgBAFQgCAPgDAGIgBACgAgQAhQgBgKgDgJIABgCIACAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAFATIgBACIgDABIgBAAIgBgBgAAqALIgBAAIAAgLIgqAAIAAALIgBAAIgEAAIgBAAIAAgPIABgBIA1AAIABABIAAAPIgBAAgAgEgNIgBgBIAAgFIABgBIASAAIAAgKIgVAAIgBgBIAAgEIABgBIAVAAIAAgDQAAgIgBgDIAIABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAIgBACIAAALIAbAAIABABIAAAEIgBABIgbAAIAAAKIAXAAIABABIAAAFIgBABg");
	this.shape_81.setTransform(244.6,160.1);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#0943BA").s().p("AgEAuIgGgEQALgGAHgJQAJgNAAgUIgBgbIgCgMIAIABQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIgBAFIACAeQAAAXgKAMQgHAKgJAHIgCAAIgBAAgAgVANQgDgGAAgNIADgbQABgHAAgFIAIADIABABIAAACIgCAEQgDANgBANIABALIAIgOIADAEQAAABAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIgHANIAAAEIgBACIgGABQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBg");
	this.shape_82.setTransform(233.1,160.2);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#0943BA").s().p("AAHAtIgEgEQAOgCAIgGQAKgHAAgLQAAgPgTgDQgLASgJALIACAGIgBACIgEACQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIgCgGQgMAKgKAAQgKAAAAgMQAAgJAHgJQAIgKAMgEIABgSIgOABIgFgBQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgFIAWAAIABgKIgBgIIAJACIABACIgCAGIgBAHQAOgBAQgEIABABIABAEQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQgOADgRACIgBAQQAJgDAKAAIACgKIAGADIACACIgCACIgBADQALACAHAHQAHAGAAAKQAAAXghAIQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBgAgjAbQAAAGAFAAQAHAAALgJQgDgMAAgLQgUALAAAPgAgIAAQAAAKACAJQAIgLAHgMQgJAAgIAEg");
	this.shape_83.setTransform(221.8,160.1);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#0943BA").s().p("AgKAHQAAgWAagOIAAgBIgsAIIgHACIgCABQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIgDgIIAOgBIBEgKQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIABAFQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgLABgGACQgNAFgIAKQgGAKAAAJQAAAXAfADQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAABIgBAFQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAQgmgEAAgdg");
	this.shape_84.setTransform(210.3,160.4);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#0943BA").s().p("AgfAWIACgxQABgLgCgGIAJACIACACIgCAOIgCAvQAAAJADAEQADADAHAAQATAAAUgVIADAIIgCACQgUATgVAAQgUAAAAgXg");
	this.shape_85.setTransform(199.7,160.1);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#0943BA").s().p("AgfAYQAAgPAWgLQgFgPgBgPIgDgLIAJABIACACIgBAEIABAHIAFAXIASgKIAHgFIAFAGQABAAAAABQAAABAAAAQAAABgBAAQAAAAgBAAIgKAEIgYALQgRAJAAALQAAAHAHADQAGADAMAAQAPAAAOgDQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIABAGQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgTACgMAAQgfAAAAgUg");
	this.shape_86.setTransform(187.7,159.9);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#0943BA").s().p("AgnAFQgCgNAAgQIgBgLIAJACIABABIgBACIgBALQAAAKACAOQABAKAEAGQADAHAFAAQAGAAAGgSIADAGQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQgGARgLAAQgPAAgEgfgAAkAQQgEgWgSgPIAFgDIACAAQASAQAEAVIAAACIgGACQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBg");
	this.shape_87.setTransform(176.6,160.3);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#0943BA").s().p("AgiAhQAAgGAFgEQAGgEAKAAIAMABIgBgSQgNABgNgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgBgEQALACARgBIAAgRQgSABgMgBIgBgBIgBgGQARABAPAAIAAgMIgBgIQADAAAEACQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAQgCACAAADIAAAKQALAAARgDQAAAAAAgBQABAAAAAAQAAAAAAABQAAAAAAAAIAAAFQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAgBAAQgOACgOABIAAARQANgBAMgDIABABIAAAFIgBABQgMABgNABIABATQAQAFAOAKIABACQgBADgCACQAAAAAAAAQgBABAAAAQAAAAAAAAQAAgBgBAAQgNgKgNgEQAAASgSAAQgUAAAAgOgAgcAhQAAAHANAAQAIAAAEgEQACgDAAgGIgMgCQgPAAAAAIg");
	this.shape_88.setTransform(165,160.1);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#0943BA").s().p("AgiAzIgBgBIAAg9IgKAMIgCABIgBgBQAAgBgDgCQAQgRAJgXIABgIIAHADIACABIgEAGIgIASIAABIIgBABgAgVAtIgBgBIAAgFIABAAIAeAAIAAgdIgWABIgBgBIAAgFIABgBIAWAAIAAgVIgaAAIgBgBIAAgFIABgBIBAAAIABABIAAAFIgBABIgfAAIAAAVIAaAAIABABIAAAFIgBABIgagBIAAAdIAjAAIABAAIAAAFIgBABgAATgeQgJgIgKgFIAAgCIADgCQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAIAEALAIQAAABABAAQAAAAAAAAQAAAAgBABQAAAAAAAAIgCADIgCABIAAAAg");
	this.shape_89.setTransform(153.5,160.1);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#0943BA").s().p("AAEAkIgEgEQAkgHAAgbQAAgMgJgIQgIgIgNAAIgCAAQgDAegKARQgHAMgKAAQgGAAgGgHQgEgHAAgMQAAgPANgMQANgNATAAQATAAALAKQALAKAAARQgBAcgjAJIgCABQAAAAgBAAQAAgBAAAAQAAAAAAAAQAAAAgBgBgAgYgTQgLAKAAAMQAAAJADAFQADAEADAAQAGAAAFgIQALgSACgZQgOACgIAJg");
	this.shape_90.setTransform(142.2,160.4);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#0943BA").s().p("AAqAvQgjgWgHgnQgFAogkAVIgCABQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIgFgEQAXgLAMgVQALgSAAgZIgBgOIAHABQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAACIgBAGIAAAGQAHAxAoAXIgEAEIgCACg");
	this.shape_91.setTransform(130.8,160.1);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#0943BA").s().p("AAHAMQgIgMgLgHIgBAAIAAgBIAEgEIACgBIABABQAKAIAJALIABABIgBACIgEADIgBAAg");
	this.shape_92.setTransform(115.8,164);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#0943BA").s().p("AgrAwIgBgBIAAhdIABgBIAmAAIAAABIAAAhIAAABIggAAIAAA7IgBABgAglgSIAZAAIAAgJIgZAAgAglghIAZAAIAAgIIgZAAgAAZAtIgCgFIAJAAIAFgBQAAAAAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIAAgvIghAAIgBgBIAAghIABgBIAnAAIABABIAABSQAAAGgDACQgCADgMAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAgAAKgSIAcAAIAAgJIgcAAgAAKghIAcAAIAAgIIgcAAgAgRAoIgBgBIAAgpIABgBIALAAIALAAIAMAAIABABIAAAnIgBABIgFAAIgBgBIAAgEIgXAAIAAAGIgBABgAgMAbIAXAAIAAgLIgXAAgAgMALIAXAAIAAgKIgXAAg");
	this.shape_93.setTransform(108.1,160.3);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#0943BA").s().p("AAFAkIgFgEQAjgHAAgbQAAgMgIgIQgJgIgMAAIgCAAQgDAegKARQgHAMgKAAQgHAAgEgHQgGgHAAgMQAAgPAOgMQAMgNAUAAQATAAALAKQALAKgBARQABAcgkAJIgCABQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAAAAAgBgAgYgTQgLAKAAAMQAAAJADAFQACAEAEAAQAGAAAEgIQAMgSACgZQgOACgIAJg");
	this.shape_94.setTransform(96.7,160.4);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#0943BA").s().p("AgRAXIABgNIgSgEQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgEQAHABANACIACgSIgTgEIgBgBIAAgHQAGADAPACIADgOQABgEgBgGIAJADIAAACIAAABIgCAGIgCANIAOgBIABABIgBAGIAAABQgJABgGgBIgDARQAIABAJgBQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAAAGQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgSAAIgBANQAAAQAQAAQAJAAAGgEQAIgFgBgIQAAgLgKgKIAHAAQAAAAAAAAQABgBAAAAQAAAAAAABQABAAAAAAQAKAJgBAMQAAALgIAHQgJAGgMABQgYAAAAgYg");
	this.shape_95.setTransform(85.3,160.1);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#0943BA").s().p("AABAzIgBgBIAAgbIgvABIgBgBIAAgFIABgBIASAAIAAgYIABgCIAcABIAAgTIgXAAQgIALgHAGIgBACIgCgCIgEgDQAOgMAJgRIACgIIAHACQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIgBABIgDAFIgEAHIA+AAIABABIAAAEIgBABIgjAAIAAATIAegBIABACIAAAEIgBABIgeAAIAAATIApAAIABABIAAAFIgBABIgpgBIAAAbIAAABgAgWARIAWAAIAAgTIgWAAg");
	this.shape_96.setTransform(74,160.1);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#0943BA").s().p("AgCAyIgBgBIAAgyIgsABIAAgBIAAgGIAAgBIAsAAIgBgpIAGABQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIgBACIgBALIAAAaIAtAAIABABIAAAGIgBABIgtgBIABAyIgBABg");
	this.shape_97.setTransform(62.6,160.1);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#0943BA").s().p("AghAzIgBgBIAAg9QgFAIgFAEIgCABIgBgBIgDgCQARgTAHgWIACgIIAGADIACABIgBACIgDAEIgHARIAABJIgBABgAATAuIgCgEIALAAQAGAAAAgFIAAhGIgxAAIgBgBIAAgFIABgBIBBAAIABABIAAAFIgBABIgJAAIAABHQAAAGgDADQgDACgNAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBgAgLAaIgBgBIAAgnIABgBIAKAAIAJAAIAKAAIABABIAAAkIgBABIgEAAIgBgBIAAgFIgSAAIAAAIIgBABgAgFALIASAAIAAgUIgSAAg");
	this.shape_98.setTransform(51.1,160.1);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#0943BA").s().p("AAGAMQgIgMgKgHIgBAAIABgBIAEgFIABABQAKAIALALIAAABIgBACIgEADIgBAAIgCgBg");
	this.shape_99.setTransform(36.2,164);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#0943BA").s().p("AgRAXIABgNIgSgEQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgEQAIABAMACIACgSIgTgEIgBgBIAAgHQAIADAOACIACgYIAIADIABACIAAABQgBACgBAEIgCANIAOgBIABABIAAAGIgBABQgJABgGgBIgDARQAIABAIgBQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIAAAGIgBABIgSAAIgBANQAAAQAQAAQAJAAAHgEQAGgFAAgIQAAgLgKgKIAHAAIACAAQAJAJAAAMQAAALgIAHQgJAGgMABQgYAAAAgYg");
	this.shape_100.setTransform(28.4,160.1);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#0943BA").s().p("AABAzIgBgBIAAgbIgvABIgBgBIAAgFIABgBIASAAIAAgYIABgCIAcABIAAgTIgYAAQgHALgHAGIgBACIgGgFQAPgNAHgQIADgIIAHACQAAAAAAABQAAAAAAAAQABAAAAAAQAAABAAAAIgBABIgHAMIA+AAIABABIAAAEIgBABIgjAAIAAATIAegBIABACIAAAEIgBABIgeAAIAAATIApAAIABABIAAAFIgBABIgpgBIABAbIgBABgAgWARIAWAAIAAgTIgWAAg");
	this.shape_101.setTransform(17.1,160.1);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#0943BA").s().p("AghAzIgBgBIAAg9QgFAIgFAEIgCABIgBgBIgDgCQARgTAHgWIACgIIAGADIACABIgBACIgDAEIgHARIAABJIgBABgAATAuIgCgEIALAAQAGAAAAgFIAAhGIgxAAIgBgBIAAgFIABgBIBBAAIABABIAAAFIgBABIgJAAIAABHQAAAGgDADQgDACgNAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBgAgLAaIgBgBIAAgnIABgBIAKAAIAJAAIAKAAIABABIAAAkIgBABIgEAAIgBgBIAAgFIgSAAIAAAIIgBABgAgFALIASAAIAAgUIgSAAg");
	this.shape_102.setTransform(5.6,160.1);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#0943BA").s().p("AhDA0QgMgTgCgdIgBgWQAAgcADgZIAUAEQAAADgFAAQgEAaAAAXIABASQACAZAJAPQAIAOAMgBQAMAAANgpQAEAEAHAEQgQAwgUAAIgBABQgSAAgMgUgAATgxIAJgLQAWAMAOAUQAPAVAEAYIgPAFQgHgwgqgXg");
	this.shape_103.setTransform(185.6,123);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#0943BA").s().p("Ag1BOQgMgIAAgNQAAgOANgHQANgIARAAQALAAAJACIAAgdIgTAAQgYABgKgCQgJgFAAgIQAAgKASgLIAJAFQgNAIAAAGQAAAEAHACIAbABIANAAIgBgkIhFAAIAAgOIBFABIgBgcIASABQAAAEgGABIAAAVQApgCAYgGIACAOQgUAEgvADIABAkQAigCAVgGIACANQgWAEgjABIACAgQAbAJAeAWIgIALQgYgTgYgJIAAAJQgBAdggAAQgUABgLgIgAgrAsQgKAFAAAHQABAJAIAFQAJAEANAAQAVAAAAgUIAAgMQgMgDgKAAQgMAAgIAFg");
	this.shape_104.setTransform(165.8,122.5);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#0943BA").s().p("Ag9BbIAAhvQgJAQgOAOIgHgKQAfgiARg2IAQAGQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgHASgLAXIAFABQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIAACAgAgiBTIAAgMIA5AAIAAg0IgtAAIAAgNIAtAAIAAgrIgzAAIAAgMIBDAAQgOgPgagQIAGgKQAeARAOAOIgIAKIAxAAIAAAMIg2AAIAAArIAwAAIAAANIgwAAIAAA0IA4AAIAAAMg");
	this.shape_105.setTransform(146.1,122.6);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#0943BA").s().p("AgkBQQgUgGAAgQQAAgGAEgJIgJACQgJAAgHgHQgHgIAAgNQAAgRAKgIQAJgKAMAAQAJAAAEAGIADgcIgqAAIAAgMIAqgBIABgdIAUACQgBADgEABIgCAWQAXgCASgGIACAOQgUAFgYACIgDApIAAAFQAAATgJAMQgGALAAAHQAAAKALAEQAIADASAAQAdAAANgFQANgGAAgPQAAgQgSgWIAMgFQAVAZAAAVQAAAYgaAHQgZAEgSAAQgVAAgLgDgAhEAAQgFAFAAALQAAAIAEAFQAEAFAGAAQALAAAFgMQADgIAAgHQAAgOgMAAQgKAAgGAHgAAbgeIACgMQAiADAWALIgEANQgUgLgigEg");
	this.shape_106.setTransform(127.2,122.5);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#0943BA").s().p("AhaBJQAOgJARgPIAAgyIgdAAIAAgMIAqAAIAAA+QAKAPAVAFQAOADAfAAQAmAAAXgCQgDAGgBAIIg3ABQgiAAgOgDQgXgFgNgRIgcAYQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAgAAYgaQgPA4glAaQgFgHgEgCQAngbANg/IAGABIgEgaIgiAAIAAgNIAtAAQAJBkA0AbIgLAKQgngWgPg8gAhVhOIAKgIQAXAPAMAQIgLAIQgLgQgXgPg");
	this.shape_107.setTransform(107.3,122.8);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#0943BA").s().p("AgNBMQAXgMAKgUQAIgRAAgdIAAgQIgzACIAAgOIAzgBIgDg2IAUABQAAAEgFABIACAvQAXgBAPgFIABAOQgUAEgTABIAAAQQAAAggJAUQgLAYgZANQgEgGgGgEgAhQAJQAAgkAJgyIATADQgBADgEABQgKAsAAAiQAAAXACAKQAIgRAMgWIAJAKQgXApAAAIIABAIIgNACQgJgZAAglg");
	this.shape_108.setTransform(88.1,122.7);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#0943BA").s().p("AgQBaIAAg6IgSAMQgEgHgDgDQASgJARgQQAOgOAIgPIASABQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQAXAdAlATIgIALIgOgJIAAA4IgNAAIAAgHIg7AAIAAAIgAgDBHIA7AAIAAggIg7AAgAgJAbIBGAAQgYgRgNgSQgNARgUASgAhVBPQATghANgfIALAHQgQAngOAWIABADIAAACgAgjgKQAWgNANgWIANAFQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgPAXgUANgAhagYIAHgKQAYAJAMAKIgIAMQgNgMgWgJgAAlgnIAJgHQAZATANAPIgKAIQgNgRgYgSgABIgiIAAgVIhcAAIAAAVIgMAAIAAggIAxAAIAAgXIASABQgBACgDABIAAATIA2AAIAAAggAhRhOIAIgKQAWAKANAMIgHAKQgOgMgWgKg");
	this.shape_109.setTransform(68.4,122.6);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#0943BA").s().p("AhMANQAAghAKg7IAVADQgBAEgGgBQgKAxAAAlQAAAcADAKIAOglIAJAJIgRAoIgCAJIABAGIgNADQgJgaAAgqgAATA/QghgFAAgcQAAgPARgUIAMAFQgPAPAAAOQAAAPASAFQALADAXAAIAZgBIAAAOIgVAAQgYAAgNgCgAgLg0QAtgCAmgGIABANQgiAHgyABg");
	this.shape_110.setTransform(48.8,122.8);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#0943BA").s().p("AAwA4QgPAVgTANQgBgCgIgGQAXgPARgaQgHgggCg5IhEAAIAAgMIBDAAIAAgdIAQABQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIAAAZIArAAIAAAMIgrAAQACAtAFAbQALgVAIgeIAQAEQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAQgKAlgRAbQAIAjALAAQAFAAACgeQADAFAGADQgCAUgEAHQgDAHgJAAQgRAAgJgigAgnA/QAYgHAmgOIADALQgiAOgWAHIgCADgAhbAxIAagJIAAhDIgWAAIAAgMIAWAAIAAgxIAQABQAAABAAAAQAAABgBAAQAAAAgBABQgBAAAAAAIAAAtIAUAAIAAAMIgUAAIAAA/IAUgIIACAMIg0AVQAAAAAAABQAAAAgBAAQAAABAAAAQgBABgBAAgAgaAeIAAg4IAvAAIAAA4gAgPATIAaAAIAAgiIgaAAgAA3hSIAHgHQAQAIALALIgIAIQgOgNgMgHg");
	this.shape_111.setTransform(29.4,122.6);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#0943BA").s().p("AAOBYQgOAAgGgFQgGgFAAgPIAAhAIgUAGIgFgKIAZgKIAAg1IAOABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAAAAAIAAAsIAbgLIAAg3IAQABQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAIAAAtIAfgNIADgCIALADIgCADQAAA/gCAKQgCAJgGADQgFACgQAAQgBgHgDgFIAOABQAGgBABgFQABgIAAg0IgeANIAABJIgMAAIAAhEIgbANIAABFQAAAIABADQADACALAAIAxAAQAJAAADgFQACgGABgSQAIAFAEABQgBAUgFAIQgGAHgPAAgAhaAvIAbgKIAAg/IgYAAIAAgNIAYAAIAAguIAQABQAAABAAAAQAAAAgBABQgBAAAAAAQgBAAgBAAIAAArIAWAAIAAANIgWAAIAAA5IAXgJIACAMIg3AYQAAABAAABQgBAAAAABQAAAAAAAAQgBAAAAABg");
	this.shape_112.setTransform(9.8,122.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,417.4,225.4);


(lib.imgstars = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0943BA").s().p("AgGBWQgFgOgHgQQgIgSgFgFQgGgGgPgIIgWgMQgEgCAAgFQAAgEAEgBQAigTAKgJQAKgKAOgqQADgGADAAQAFAAACAGQAOAqAKAKQAIAHAkAVQAEABAAAEQAAAFgEACQgeAOgMALQgFAFgIATIgNAeQgBAFgGABQgEgBgCgFgAgSgWQgIAIgbAOQAYAMAJAJQAJAKALAeQANgfAJgJQAKgLAWgKQgbgOgHgIQgIgHgMgeQgMAfgGAGg");
	this.shape.setTransform(361.6,87.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0943BA").s().p("AgGBWQgQgsgJgJQgGgGgPgJIgWgLQgEgCAAgFQAAgEAEgCQAhgQALgLQAKgKAOgqQACgFAEgBQAFABACAFQAOAqAKAKQALALAhAQQAEACAAAEQAAAEgEADIgVALQgPAJgGAFQgKAKgQAsQgCAGgFAAQgEAAgCgGgAgTgVQgHAHgbAOQAaANAHAJQAJAIALAfQANggAJgIQAKgLAWgKQgbgNgIgJQgGgGgNgfQgLAdgIAJg");
	this.shape_1.setTransform(879.8,114.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0943BA").s().p("AgGBWQgQgsgKgJQgFgGgPgIIgWgMQgEgCgBgFQABgEAEgCQAggPAMgMQAIgJAQgrQACgFAEgBQAFABACAFQAQAsAIAIQALAMAhAPQAEACABAEQAAAFgGACQgeAOgKALQgJAIgSAuQgCAGgFAAQgEAAgCgGgAgSgVQgIAGgaAPQAYAMAJAKQAHAHAMAgQAMgfAKgJQAKgKAWgLQgagNgJgJQgHgIgMgdQgKAcgIAKg");
	this.shape_2.setTransform(298,401.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0943BA").s().p("AgGBWQgQgsgJgJQgKgJghgRQgEgDAAgEQAAgEAEgCQAigSAKgJQAKgKAOgqQADgGADABQAFgBACAGQAOAqAKAKQAIAIAkATQAEACAAAEQAAAFgEACQgeAOgMALQgFAFgIASQgIAQgFAPQgBAGgGgBQgEABgCgGgAgSgWQgIAJgbANQAYANAJAIQAJAKALAeQAMgeAKgLQAIgHAYgNQgbgNgIgJQgHgHgMgeQgMAfgGAGg");
	this.shape_3.setTransform(394.6,273.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0943BA").s().p("AgGBWQgQgsgJgJQgKgKghgQQgEgCAAgFQgBgDAFgDQAggPAMgMQAIgJAQgrQABgFAFAAQAFAAACAFQAQArAIAJQAMAMAgAPQAEADAAADQAAAEgEADIgVALQgPAIgGAGQgJAJgRAtQgCAFgFAAQgFAAgBgFgAgTgWQgKAKgYAMQAXAMAKAJQAIAIAMAgQAOghAIgIQAHgHAYgNQgZgNgJgJQgJgKgKgbQgKAbgJAKg");
	this.shape_4.setTransform(544.3,189.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0943BA").s().p("AgGBWQgPgrgKgKQgJgJgigRQgEgDAAgEQAAgEAEgCQAjgSAJgJQAJgJAPgrQACgFAEAAQAFAAACAFQAOAqAKAKQAJAJAjASQAFACgBAEQAAAFgEACQgeAOgMALQgJAKgRAsQgBAGgGgBQgEABgCgGgAgSgVQgIAHgbAOQAXAMAKAKQAJAHALAgQAMgfAKgKQAHgGAZgOQgagNgIgIQgIgJgMgdQgKAcgIAKg");
	this.shape_5.setTransform(615.5,105.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0943BA").s().p("AgGBWQgPgrgKgKQgLgKgggQQgEgDAAgEQAAgDAEgDQAhgQALgLQAJgJAPgrQABgFAFAAQAGAAABAFQAPAqAJAKQALALAhAQQAEADAAADQAAAFgEACQgiASgIAHQgFAFgIASQgIARgFAOQgBAFgGAAQgEAAgCgFgAgTgWQgJALgZALQAbAPAGAHQAJAIALAfQANggAJgJQAIgIAYgMQgYgLgLgLQgIgJgLgcQgLAegIAHg");
	this.shape_6.setTransform(490,69.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(290,60,597.8,350.3);


(lib.imgillust = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0943BA").s().p("AgWAoQgGAAgCgGQgIgqAHgTQAAgDADgBQALgIATAAQAOAAANADQAFACABAFQABAZgHAjQgBADgDACQgJAEgUAAgAgRgTQgEAQAGAbIALAAQAMAAAGgBQAFgYAAgVIgRgBQgLAAgIAEg");
	this.shape.setTransform(29.4,28.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0943BA").s().p("AgSAmQgGAAgCgFQgEgOgCgTQgBgTAEgNQACgFAGAAQAgAAAQAEQAFACABAFQABAVgGAfQgBADgDADQgMAGgeAAgAgMAWQAOgBALgDQAEgVAAgQQgNgCgTAAQgDAUAGAXg");
	this.shape_1.setTransform(51.7,47.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0943BA").s().p("AghAiQgLgdAJgiQABgEAEgCQAdgJAhALQAEABACAFQADAOgBANQgBASgHAMQgBADgDABQgJAEgNAAIgHAAQgQgBgGACIgDABQgGAAgBgGgAgUgUQgGAUAGAWIATgBQAOABAGgCQAIgRgEgWQgOgEgKAAQgKAAgJADg");
	this.shape_2.setTransform(16.8,28.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0943BA").s().p("AgLAlIgNgCQgDAAgCgCQgDgCAAgDIAAgQQgDgiAEgLQACgGAGABIAUABQAZABAGACQADAAACADQACACgBADIgCAUQgDAfgCAGQgBACgCACQgIAEgLAAIgQgCgAgRALIAAAKIAJACIANABQAFAAAEgBIADgeIABgOIgkgCQgBAPACATg");
	this.shape_3.setTransform(43,27.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0943BA").s().p("AgBAFQgFAAAAgFQAAgDAFAAIADAAQAFAAAAADQAAAFgFAAg");
	this.shape_4.setTransform(37.5,6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0943BA").s().p("Ah7EdIgDABIgBAAIgDAAIggAAQgpAAgQgDQgGgBAAgGQABgkgLiYQgLiRgHg7QggAAgFgBQgFgBgBgFQgThKAEhGQAAgGAHgBQBCgLCTAAQB3AAB5AHQB/AIAPAJQAEADAAAEQACBYgTAzQAAADgFACQgMADgRAAQgLAAgPgCQgBAcgEAyQgFA9AAAiQAVgBAbAEQAeAEAVAIQAGADgBAGQgPBXgMBcQgBAHgHAAQgaADhJABQg9AAgeACIgBAAIgDAAIAAAAQhdAGhIAAIgpgBgAgkCHQg3ABgkAFQABBGAHA9QBKADB7gJIACgjQADg8gFgfQgegGgwAAIgkABgAjcBQQAKCOAAAvQAQACArAAIAPAAQgGg4gBhRIABgEQAFgJBdgDQBbgCAoAJQAFABABAFQAGAfgDBGIgBAgQASgCBBgBQA4AAAjgDIAaimQgXgHgfgDQgagDgOACQgEAAgDgCQgCgCAAgEQgBgfAGhKQAEgzABgdQgngDkFAAIiMAAQAIA6AKCJgAkokEQgDA8AQBEQAgACCZAAQEdAAAWAEIABAAIAEABQAdAEAWgDQAQgvgBhOQgYgHhsgHQh2gHh5AAg");
	this.shape_5.setTransform(31.3,29.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0943BA").s().p("AgQEWQgDgCgBgDQgDgQABggQABgSgCgPQgWAPgbAAQgdAAgZgPQgUgOgJgUQgJgVAFgYQglgBgSgcQgMgSAAgXQAAgYALgTQAPgbAagIQgUgVgDghQgDgeAOgaQAMgXAVgKQAUgKAZAGQAAhDAqgZQAVgLAZABQAXABAVAOQAdATAEAcQAagOAfAHQAcAGAUAUQAWAUAEAbQAEAagOAYQAVAJANASQANASACAWQACAUgIASQgHAPgQAMQATAUAEAcQADAcgOAaQgNAYgYAQQgbAQgfAAQgMAAgNgDQgGAPgYAHQAFAsgEAXQAAAFgFABQgYAJgUAAQgOAAgOgHgAgGDiQgBAYACAPQATAIAggLQACgWgEghIgPABQgUAAgPgHgAiOBkQACADgBAEQgHAWAHATQAGASASAMQAVAOAZgBQAcgBAUgSIACgBIABAAIAAgBIADAAIADABIACABIABABIAAAAIABABIAAACIAAAAIABAEQAHAHAOADQARADAQgDIAFgCIAEAAQAWgGABgLIAAAAIAAgBIABgBIAAgBIADgDIABAAIABgBIAEAAQAkAKAfgPQAcgNANgaQAMgVgCgWQgDgagVgUIgHgBQgIAAAAgIQABgEACgCQADgCADAAIAJABQAfgRgEgjQgCgUgNgPQgMgPgSgGIgDAAQgHACgGAAIgBAAQgHAAgBgHQAAgDACgDQACgCAEgBIAKgCIACAAQAPgXgFgXQgEgUgQgQQgUgTgagEQgcgFgXASQgEADgFgDQgFgDABgEQADgcgcgTQgQgLgSgCQgWgCgSAKQglAWAEBCIgBABQAAADgCACIgBABIgBABIgDABIgDgBQgcgKgVANQgNAIgIAQQgNAYAFAdQAFAeAXARQALAAALAHQADABACAEQABADgCADQgCAFgFAAIgDgBQgNgHgGABIgBAAQgeAAgPAbQgJARAAATQAAATAJAOQAQAYAkgCIABAAQADAAADADg");
	this.shape_6.setTransform(108.9,28.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0943BA").s().p("AgPEWQgEgCgBgDQgDgQABggQABgTgCgOQgWAPgbAAQgeAAgYgPQgUgOgJgUQgJgVAFgYQgkgBgTgcQgMgSAAgXQAAgYALgTQAOgbAbgIQgUgVgDghQgDgfAOgZQAMgXAVgKQAUgKAZAGQAAhEAqgYQAVgLAZABQAXABAVAOQAcASAFAdQAagOAfAHQAcAGAUAUQAWAUAEAaQAEAagOAZQAVAJANASQANASACAWQACAUgIARQgHAQgQALQATAVAEAcQADAbgOAbQgNAYgYAPQgaARggAAQgLAAgOgDQgHAPgXAHQAFAsgEAXQgBAEgEACQgZAJgTAAQgPAAgMgHgAgGDiQAAAeABAJQARAIAigLQACgXgEghIgPABQgWAAgNgGgAgPCqIABABIACABIABABIABABIABAGQAHAHAOADQAQACARgCIAFgDIAEABQAWgGABgLIAAgBIAAAAIABgBIAAgCIABgBIACgBIADgBIACAAIABAAIAAAAQAlAJAegOQAcgNANgaQAMgVgCgWQgDgagVgUIgHgBQgIgBAAgIQABgDACgCQADgCADAAIAJABQAOgJAIgMQAHgOgCgRQgCgUgNgPQgMgPgSgGIgQACIAAAAQgIAAgBgHQAAgEACgCQACgDAEAAIAMgCQAPgXgFgYQgEgUgQgQQgUgSgagEQgcgFgXASQgEADgFgDQgEgCAAgGQADgbgcgTQgQgLgSgCQgWgCgRAKQgmAVAEBDIgBABQAAADgCACIgBABIgBABIgCAAIgEAAQgcgKgVAMQgNAIgIAQQgMAZAEAcQAFAfAXAQQAJABANAGQAIAFgEAHQgCAEgFAAIgDAAQgOgHgFABIAAgBIAAABQgfAAgPAbQgJAQAAAUQAAATAJAOQAQAYAkgCQAEgBADAEQACADgBAEQgHAWAHATQAGASASAMQAVANAZAAQAcgBAUgSIAAAAIACgBIABgBg");
	this.shape_7.setTransform(385.6,70.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0943BA").s().p("AAMDPIgBAAQgEgBgBgEIAAAAIAAgBIgBgDIgDgbIgFAiQgCAGgFAAQgMADgIAAQgMAAgPgGQgFgBgBgGQgLhNABhSQgIAKgIADQgDABgDgBQgKgDgVgQQgEgEABgFQACgIAQgSQATgVAcgXQgUgPgLgVQgLgVAAgXQABgZAPgVQAPgVAagMQAZgNAbAAQAYAAAVAKQAVAKANASQAfArgWA/QgIATgIAKIAGAIIAbAlQAPAYAIAXIAAAEQgBAGgKAGQgIAFgIACIgEAAQgMgDgPgWIgCgDQACAmgDBTIgBAnQAAAHgHABQgHADgJAAQgTAAgPgJgAALCFQAJASADAqQANAGAPgCIABggQADhtgEghQgBgFAEgDQAEgDAFABQALAFAOATQALAPAEACIAJgEQgHgTgOgVIgZgiIgKgNQgEgHAGgFQAGgFALgYQARg1gYgjQgXgfgqAAQgWAAgXALQgVAKgMARQgMAQgBAVQAAAVALATQAMASAVANQAFACAAAFQABAEgFAEQgsAhgWAeQAKAHAGADIAHgIQAMgNAHgDQAFgBAEADQADACAAAFQgCBTALBYQANAEANgCQALgvAFgOQACgFAEgBQAFAAAEAFg");
	this.shape_8.setTransform(199.5,305.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0943BA").s().p("AgzAjQgEgBgBgFQgCgPABgcIAAgLQAAgGAGAAIAEgBQAggDASAAQAbABAWAFQAEABABADQAEAQgGAiQgBAGgEAAQgXAEgzABgAgtgTIAAAFQAAAcABAJIAUAAQArAAAYgEQAFgYgDgMQgQgEgagBQgUAAgcADg");
	this.shape_9.setTransform(241,44.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0943BA").s().p("AgaAeQgEgRAEgnQAAgEAFgCQAJgCANAAQAPAAAHAEQADABABADQADAIgBAUQgBAPABAKQABAGgGABQgCABgKAAIgeAAIgCAAQgFAAgBgFgAgNgUQgCAdABAMIAdAAIAAgoQgIgCgHAAIgNABg");
	this.shape_10.setTransform(255.6,44.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0943BA").s().p("AgUAcQgEgBgBgEQgCgXADgWQAAgEAEgBQAIgDAMAAQANAAAIADQADABABAEQAEAagHAVQAAAAgBABQAAAAAAABQgBAAAAABQgBAAgBAAQgGADgMAAQgLAAgJgDgAgMgQQgCARACAQQAMADAKgDQAEgNgBgUIgNgCQgGAAgGACg");
	this.shape_11.setTransform(255.7,30.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0943BA").s().p("AgVAfIgdgBQgEAAgBgEQgEgKgBgQQAAgMADgOQABgEADgBQAIgBARAAQAVAAAZACQAbACALADQAEACAAAEQABAHgCATIgCAUQAAAFgGABIgUAAIg0gCgAgugTQgDAUAEAQIAZACQAzACAOgBIABgOIACgUQgggGgsAAg");
	this.shape_12.setTransform(241.2,30.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0943BA").s().p("AgVAbQgFgBAAgFIgCgVQgCgNABgHQAAgFAFgBQAPgEAeAAIACAAQAGABABAFQABAYgFAXQAAADgDACQgFACgMAAQgOABgNgEgAgQgOIACAOIABAQQAUACAHgBQADgSAAgPIghACg");
	this.shape_13.setTransform(256,17.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0943BA").s().p("AgYAeIgegCQgGAAAAgGQgBgdABgPQABgFAFgBQAzgGA4AFQAFABABAEQACAKAAAOQABAQgCAKQgBAFgFABIgXABQgWAAghgDgAgvgQQgBARABAPQA2AEAYAAIARgBQACgTgDgRQgWgCgVAAQgZAAgaADg");
	this.shape_14.setTransform(241.6,17.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0943BA").s().p("AhFEGIhUgEQgFAAgBgFQgMgfgDjaQgCimADhZQAAgHAHAAIBLgDQBMgEAmAAQBRAAA+ANQAEAAABAFQAGAjgCBHIAABPQADEVgOAqQgBAEgFABQgvAEgwAAQgkAAhggEgAhbj4IhEADQgDBoACCbQADDBAJAmIBQADQBgAEAjABQAtAAAsgFQAMgvgDkHIAAhPQAChDgFggQg5gLhOAAQgmAAhMADg");
	this.shape_15.setTransform(246.8,32.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8,p:{rotation:0}},{t:this.shape_7,p:{rotation:0}},{t:this.shape_6,p:{rotation:0,y:28.5}},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8,p:{rotation:15}},{t:this.shape_7,p:{rotation:15}},{t:this.shape_6,p:{rotation:15,y:28.6}},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},39).wait(41));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,408.4,327.1);


(lib.imgframe = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAvgtQhDhAhhgCIDrAAIAADfQgChfhFg+g");
	this.shape.setTransform(1028.1,11.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah1B8IAAj3QACBiBFBIQBFBLBfACg");
	this.shape_1.setTransform(10.9,612.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjyjyIHlAAInlHlg");
	this.shape_2.setTransform(24.4,24.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjyDzIHlnlIAAHlg");
	this.shape_3.setTransform(1016.6,600.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1040,624.1);


(lib.imgbubble = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0943BA").s().p("AgnAoQgRgRAAgXQAAgWARgRQARgRAWAAQAXAAARARQARARAAAWQAAAXgRARQgRARgXAAQgWAAgRgRgAgcgcQgMANAAAPQAAARAMAMQANAMAPAAQARAAAMgMQAMgMAAgRQAAgPgMgNQgMgMgRAAQgPAAgNAMg");
	this.shape.setTransform(845.8,149.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0943BA").s().p("AghAiQgOgOAAgUQAAgSAOgPQAOgOATAAQAUAAAOAOQAOAPAAASQAAAUgOAOQgOAOgUAAQgTAAgOgOgAgWgVQgJAJAAAMQAAANAJAKQAKAJAMAAQANAAAJgJQAKgKAAgNQAAgMgKgJQgJgKgNAAQgMAAgKAKg");
	this.shape_1.setTransform(642.7,93.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0943BA").s().p("AgWAXQgKgKAAgNQAAgNAKgJQAJgKANAAQANAAAKAKQAKAJAAANQAAANgKAKQgKAKgNAAQgNAAgJgKgAgOgNQgFAGAAAHQAAAIAFAGQAHAGAHAAQAIAAAHgGQAFgGAAgIQAAgHgFgGQgHgGgIAAQgHAAgHAGg");
	this.shape_2.setTransform(732.5,49.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0943BA").s().p("AgWAXQgKgKAAgNQAAgMAKgKQAJgKANAAQANAAAKAKQAKAKAAAMQAAANgKAKQgKAKgNAAQgNAAgJgKgAgNgOQgHAHAAAHQAAAIAHAHQAGAFAHAAQAIAAAGgFQAHgHAAgIQAAgHgHgHQgGgFgIAAQgHAAgGAFg");
	this.shape_3.setTransform(986.8,245.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0943BA").s().p("AgWAXQgKgKAAgNQAAgNAKgJQAKgKAMAAQAOAAAJAKQAKAJAAANQAAANgKAKQgJAKgOAAQgMAAgKgKgAgNgOQgGAHAAAHQAAAIAGAGQAGAGAHAAQAIAAAHgGQAGgGAAgIQAAgHgGgHQgHgGgIAAQgHAAgGAGg");
	this.shape_4.setTransform(951.3,218.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0943BA").s().p("AgmAYQgLgRAFgQQAEgTARgKQALgHAMAAQAaAAAOAWQAKARgFARQgEASgRAKQgMAHgMAAQgZAAgNgWgAgOgYQgLAGgDAMQgDAKAGALQAJAPAQAAQAGAAAJgEQALgHADgMQADgLgHgKQgIgPgRAAQgHAAgHAFg");
	this.shape_5.setTransform(296.9,18.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0943BA").s().p("AgmAYQgLgRAFgQQAFgTAQgKQAMgHALAAQAaAAAOAWQAJARgEARQgEATgRAKQgLAGgNAAQgZAAgNgWgAgPgYQgJAGgEANQgDAJAGAMQAKAOAPAAQAIAAAIgEQAKgHADgMQADgLgHgKQgJgPgQAAQgHAAgIAFg");
	this.shape_6.setTransform(964.5,180.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0943BA").s().p("AgnAoQgRgRAAgXQAAgWARgRQAQgRAXAAQAYAAARARQAQARAAAWQAAAXgQARQgRARgYAAQgXAAgQgRgAgcgcQgMANAAAPQAAARAMAMQAMAMAQAAQARAAAMgMQAMgMAAgRQAAgPgMgNQgMgMgRAAQgQAAgMAMg");
	this.shape_7.setTransform(98.8,335.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0943BA").s().p("AgnAoQgRgRAAgXQAAgWARgRQARgRAWAAQAXAAARARQARARAAAWQAAAXgRARQgRARgXAAQgWAAgRgRgAgcgcQgMANAAAPQAAARAMAMQAMAMAQAAQARAAAMgMQAMgMAAgRQAAgPgMgNQgMgMgRAAQgQAAgMAMg");
	this.shape_8.setTransform(212.5,335.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0943BA").s().p("AgnAoQgRgRAAgXQAAgWARgRQARgRAWAAQAXAAARARQARARAAAWQAAAXgRARQgRARgXAAQgWAAgRgRgAgcgcQgMAMAAAQQAAARAMAMQAMAMAQAAQARAAAMgMQAMgMAAgRQAAgQgMgMQgNgMgQAAQgQAAgMAMg");
	this.shape_9.setTransform(467.2,90.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0943BA").s().p("AgTAUQgIgJAAgLQAAgLAIgHQAJgJAKAAQALAAAJAJQAIAHAAALQAAALgIAJQgJAIgLAAQgKAAgJgIgAgIgIQgDAEAAAEQAAAFADADQAEAEAEAAQAFAAADgEQAEgDAAgFQAAgEgEgEQgDgDgFAAQgEAAgEADg");
	this.shape_10.setTransform(458.5,119.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0943BA").s().p("AgoBJQgTgKgMgTQgSgeAIggQAJgiAdgTQAVgMAWAAQAWAAATALQATAKAMATQASAegIAgQgJAigdATQgVAMgXAAQgVAAgTgLgAgig5QgYAPgHAbQgGAaAOAYQAKAQAPAIQAQAJAQAAQASAAARgKQAYgPAHgbQAGgagOgYQgKgQgPgIQgPgJgSAAQgRAAgRAKg");
	this.shape_11.setTransform(599.2,27.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0943BA").s().p("AgWAXQgKgKAAgNQAAgMAKgKQAKgKAMAAQANAAAKAKQAKAKAAAMQAAANgKAKQgKAKgNAAQgMAAgKgKgAgLgLQgFAFAAAGQAAAGAFAGQAFAFAGAAQAHAAAFgFQAFgGAAgGQAAgGgFgFQgFgEgHAAQgGAAgFAEg");
	this.shape_12.setTransform(3.3,51.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0943BA").s().p("AgnAYQgKgRAFgQQAEgTARgKQALgHAMAAQAZAAAOAWQALARgFARQgFATgQAKQgLAGgNAAQgZAAgOgWgAgPgYQgLAGgCANQgEAKAHALQAJAOAQAAQAIAAAHgEQALgIADgLQADgKgHgLQgJgPgQAAQgHAAgIAFg");
	this.shape_13.setTransform(55.8,4.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0943BA").s().p("AgoBJQgTgKgMgUQgSgdAIggQAJgjAdgSQAUgMAXAAQAWAAATALQATALAMASQASAegIAgQgJAigeATQgTAMgYAAQgVAAgTgLgAgig5QgYAPgHAbQgHAaAPAYQAKAQAPAIQAPAJARAAQASAAARgKQAYgPAHgbQAGgagOgYQgKgPgPgJQgQgJgRAAQgRAAgRAKg");
	this.shape_14.setTransform(60.4,42.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,990.2,341.1);


(lib.imgbg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.instance = new lib.bmpbg();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1040,624);


(lib.effect = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// stars
	this.instance = new lib.imgstars("synched",0);
	this.instance.setTransform(212.8,132.7,1,1,0,0,0,246.8,173.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).to({alpha:0},15).to({alpha:1},15).to({alpha:0},15).wait(1));

	// bubble
	this.instance_1 = new lib.imgbubble("synched",0);
	this.instance_1.setTransform(453.2,210.8,1,1,0,0,0,453.2,210.8);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},29,cjs.Ease.get(1)).to({alpha:0},30).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,990.2,369.3);


// stage content:



(lib.mansion = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// frame
	this.instance = new lib.imgframe("synched",0);
	this.instance.setTransform(520,312,1,1,0,0,0,520,312);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(60));

	// stars
	this.effect = new lib.effect();
	this.effect.setTransform(23.1,41.6);
	this.effect._off = true;

	this.timeline.addTween(cjs.Tween.get(this.effect).wait(59).to({_off:false},0).wait(1));

	// illust
	this.illust = new lib.imgillust();
	this.illust.setTransform(286.5,114.5,1,1,0,0,0,144.6,76.9);
	this.illust._off = true;

	this.timeline.addTween(cjs.Tween.get(this.illust).wait(59).to({_off:false},0).wait(1));

	// text
	this.instance_1 = new lib.imgtext("synched",0);
	this.instance_1.setTransform(185.9,262.4,1,1,0,0,0,137.1,138.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({y:252.4,alpha:1},49,cjs.Ease.get(1)).wait(1));

	// bg
	this.instance_2 = new lib.imgbg("synched",0);
	this.instance_2.setTransform(520,322,1,1,0,0,0,520,312);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:312,alpha:1},59,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(520,312,1040,634);

var obj = { lib: lib, img: img, createjs: cjs, ss: ss  };
return obj;
})(lib = lib||{}, images = images||{}, createjs = window.createjs||{}, ss = ss||{});
var lib, images, createjs, ss;
