<header>
    <div class="headInner">
        <h1 class="logo"><a href="top.php"><img src="imgs/logo.png" alt="遠鉄アシスト株式会社" height="100%"></a></h1>
        <!--button class="menuBtn"><img src="imgs/h_menu.png" width="100%"></button-->
    </div>
    <div id="dl-menu" class="dl-menuwrapper">
        <button class="dl-trigger"><img src="imgs/h_menu.png" width="100%"></button>
        <ul class="dl-menu">
            <li><a href="service.php">サービス案内</a></li>
            <li><a href="company.php">会社案内</a></li>
            <li><a href="pdf/privacy.pdf" target="_blank">個人情報保護方針 (pdf)</a></li>
            <li><a href="pdf/douisho.pdf" target="_blank">採用応募者同意書ダウンロード (pdf)</a></li>
            <li><a href="pdf/work.pdf" target="_blank">労働者派遣事業に係る情報提供 (pdf)</a></li>
        </ul>
    </div>
    <!-- /dl-menuwrapper -->
</header>
